config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :restaurants, only: [:index, :create, :new, :show ]  do
      resources :reviews, only: [:index, :create, :new, :show ]
  end

  # namespace :admin do
  #   resources :restaurants do
  #     resources :reviews
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [ :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(review_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @review = Review.new
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def review_params
    params.require(:restaurant).permit(:name,:address,:category,:phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # render :new
      render :template => "restaurants/show"
    end
  end

  def index
    @reviews = @restaurant.reviews
  end

  def show
    @review = Review.find(params[:id])
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<ul>
<% @restaurants.each do |restaurant| %>
  <li><%=link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</ul>

<%=link_to "New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "add restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant  details</h1>
<ul>
  <li><%= @restaurant.name %></li>
  <li><%= @restaurant.address %></li>
  <li><%= @restaurant.phone_number %></li>
  <li><%= @restaurant.category %></li>
</ul>

<%=link_to "All Reviews of #{@restaurant.name}", restaurant_reviews_path(@restaurant) %>
<h3>Reviews</h3>
<ul>
  <% @restaurant.reviews.each do |review|%>
  <li>
    <p><%=link_to "Rating: #{review.rating}", restaurant_review_path(@restaurant, review)%></p>
    <p>Content: <%= review.content%></p>
  </li>
  <%end%>
</ul>
<%=link_to "New Review", new_restaurant_review_path(@restaurant) %>
<%=link_to "All Restaurants", restaurants_path %>

<% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h1>All reviews for <%= @restaurant.name %></h1>
<% @reviews.each do |review| %>
<ul>
  <li>
    <p>Review rating: <%= review.rating %></p>
    <p>Review content: <%= review.content %></p>
  </li>
</ul>
<%end%>
<%=link_to "Go back to restaurant", restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Review details</h1>
<ul>
  <li>For restaurant: <%= @restaurant.name %></li>
  <li>Review rating: <%= @review.rating %></li>
  <li>Review content: <%= @review.content %></li>
</ul>
<%=link_to "Go back to restaurant", restaurant_path(@restaurant)  %>